In [2]:
import torch
import torch.nn as nn
import math
loss = nn.CrossEntropyLoss()
input = torch.randn(1, 5, requires_grad=True)
target = torch.empty(1, dtype=torch.long).random_(5)
output = loss(input, target)

print("输入为5类:")
print(input)
print("要计算loss的类别:")
print(target)
print("计算loss的结果:")
print(output)


输入为5类:
tensor([[ 1.7827,  0.3490,  1.0290,  1.7640, -0.2071]], requires_grad=True)
要计算loss的类别:
tensor([4])
计算loss的结果:
tensor(3.0291, grad_fn=<NllLossBackward>)


In [3]:
first = 0
for i in range(1):
    first -= input[i][target[i]]
second = 0
for i in range(1):
    for j in range(5):
        second += math.exp(input[i][j])
res = 0
res += first +math.log(second)
print("自己的计算结果：")
print(res)


自己的计算结果：
tensor(3.0291, grad_fn=<AddBackward0>)


In [4]:
import torch
import torch.nn as nn
import math
loss = nn.CrossEntropyLoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)
output = loss(input, target)

print("输入为3个5类:")
print(input)
print("要计算loss的类别:")
print(target)
print("计算loss的结果:")
print(output)


输入为3个5类:
tensor([[-0.5698, -0.4868,  0.2832, -0.4331,  1.0972],
        [ 0.0873,  0.0293, -0.3204,  0.4906,  0.9907],
        [ 1.0224,  0.1194,  1.3856, -0.1639,  1.5274]], requires_grad=True)
要计算loss的类别:
tensor([3, 4, 2])
计算loss的结果:
tensor(1.4787, grad_fn=<NllLossBackward>)


In [5]:
first = [0,0,0]
for i in range(3):
    first[i] -= input[i][target[i]]
second = [0,0,0]
for i in range(3):
    for j in range(5):
        second[i] += math.exp(input[i][j])
res = 0
for i in range(3):
    res += first[i] +math.log(second[i])
print("自己的计算结果：")
print(res/3)

自己的计算结果：
tensor(1.4787, grad_fn=<DivBackward0>)


--------------------- 
作者：tmk_01 
来源：CSDN 
原文：https://blog.csdn.net/tmk_01/article/details/80839810 
版权声明：本文为博主原创文章，转载请附上博文链接！